### ISSUE TITLE
Implement basic Map/List access

### ISSUE THREAD

**Issue by DKorchuganov** [JVMLab/toolchest#6]
Implement basic syntax to access nested Map/List data structures:

1. `$`-sign indicates a root of a data structure
2. `.key` means a Map access by a `key`
3. `[numeric-index]` like `[0]` or `[12]` means a List access by a numeric index

So for the following sample YAML data structure
```yaml
name:
  ru: 'Всероссийское музейное объединение музыкальной культуры имени М.И. Глинки'
  en: 'The Glinka National Museum Consortium of Musical Culture'
address:
  ru: 'Москва, ул. Фадеева, д.4 (метро «Маяковская», «Новослободская»)'
  en: '4 Fadeeva st, Moscow'
phones:
  - desc:
      ru: 'Заказ билетов'
      en: 'Ticket office'
    numbers:
      - url: '+74957396226'
        disp: '(495) 739-62-26'
      - url: '+74957393987'
        disp: '(495) 739-39-87'
```
a full ML-path can look like
`$.address.en` gives '4 Fadeeva st, Moscow'
